import Head from 'next/head';
import { useQuery } from 'urql';
import Product from '../components/product';
import { PRODUCT_QUERY } from '../lib/query';

export default function Home() {
  //fetch products from strapi

  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //check for the data coming in

  if (fetching) return <p>LOADING...</p>;
  if (error) <p>OH NO... {error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>The Purple Sunset</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>PRODUCTS</h1>

        {products.map((product) => (
          <Product key={product.attributes.slug} product={product} />
        ))}
      </main>
    </div>
  );
}
